server:
  port: 8081

spring:
  application:
    name: @artifactId@
  profiles:
    active: @profileActive@
#  activiti:
#    check-process-definitions: true
#    process-definition-location-prefix: classpath:/processes/
#        process-definition-location-suffixes:
#          - **.bpmn
#          - **.bpmn20.xml

  #sql自动升级管理
  flyway:
    ## 是否启用flyway
    enabled: false
    ## 编码格式，默认UTF-8
    encoding: UTF-8
    ## 迁移sql脚本文件存放路径，默认db/migration
#    locations: db/migration
    ## 迁移sql脚本文件名称的前缀，默认V
#    sql-migration-prefix: V
    ## 迁移sql脚本文件名称的分隔符，默认2个下划线__
#    sql-migration-separator: __
    ## 迁移sql脚本文件名称的后缀
#    sql-migration-suffix: .sql
    ## 迁移时是否进行校验，默认true
#    validate-on-migrate: true
    ## 将schema_version表从数据库删除后抛出异常
    ## Caused by: org.flywaydb.core.api.FlywayException:
    ## Found non-empty schema(s) `nmg-crm` without metadata table!
    ## Use baseline() or set baselineOnMigrate to true to initialize the metadata table.
    ## 设置为true，当迁移发现数据库非空且存在没有元数据的表时，自动执行基准迁移，新建schema_version表
    baseline-on-migrate: true
    #是否允许无序的迁移
    out-of-order: false
    #使用的元数据表名-->版本记录
    table: schema_version

# mybatis page helper
#pagehelper:
#  helper-dialect: mysql

# logging config
logging:
  config: classpath:config/logback-spring.xml

# actuator config
# http://localhost:8080/actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

#  self-defined actuator info
info:
  author: winjean
  version: @version@
config:
  winjean:
    age: 33
